---
title: "FDA+clusterwise_regression"
author: SpencerWang
date: "6/20/2024"
output:
  rmdformats::readthedown:
    self_contained: true
    lightbox: true
    gallery: false
    highlight: tango
    

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)  
```




# function definition
```{r}
setwd("C:/Users/Spenc/Desktop/manual_packages/FdaCluReg")
install.packages("C:/Users/Spenc/Desktop/manual_packages/FdaCluReg_0.0.0.18.tar.gz")
library(FdaCluReg)
```

## integrated simulation function 
```{r}
color_seq=c("red","blue","orange","purple","green","grey","#cd5c5c","#006400",
            "#FF00FF","#d2691e","#00FFFF","#808000","yellow","black","#FF4000")
```

##
1.并行算法撰写-sample 1 
```{r}
parallel_simulation1=function(seed_seq,method="ls",type=c(TRUE,TRUE))
{
library(FdaCluReg)
set.seed(seed_seq)
fun_1=function(t){return(sin((pi*t))*(2^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t))*(2^0.5))}#basis fun 2

function_list=list(fun_1,fun_2)#function list
sample_t=seq(0,1,0.01)#sampling time 
group_scale=c(100,100)#group scales
N=sum(group_scale)#number of samples
fda_coef_df=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df_list=list(fda_coef_df)# for multi variables
error_sd=1#standard error of observation error 

# generating X  
xij_temp=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df,sample_t=sample_t,error_sd = 0.2,seed = seed_seq)
xij_list=list(xij_temp)

## generating Y
###parameter setting  
#
N=nrow(fda_coef_df)#sample size
reg_error1=rnorm(N,0,1)*0.5#epsilon-1
reg_error2=rt(N,3)*0.5#epsilon-2
reg_error3=(rchisq(N,3)-3)*0.5#epsilon-3
#
reg_var1=rep(1,N)#sigma-1
reg_var2=0.5*(fda_coef_df[,1]+fda_coef_df[,2])#sigma-2
#
reg_coef_df=matrix(c(rep(1,N),rep(1,N/2),rep(-1,N/2)),ncol = 2)
reg_coef_df_list=list(reg_coef_df)#for multi variables
reg_intercept=rep(0,200)


##########################
yi_temp_n_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error1,seed = seed_seq,interval = c(0,1))
yi_temp_t_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error2,seed = seed_seq,interval = c(0,1))
yi_temp_chisq_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error3,seed = seed_seq,interval = c(0,1))


########################
yi_temp_n_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error1,seed = seed_seq,interval = c(0,1))
yi_temp_t_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error2,seed = seed_seq,interval = c(0,1))
yi_temp_chisq_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error3,seed = seed_seq,interval = c(0,1))

Y_list=vector("list",6);
Y_list[[1]]=yi_temp_n_homo;Y_list[[2]]=yi_temp_t_homo;Y_list[[3]]=yi_temp_chisq_homo
Y_list[[4]]=yi_temp_n_heter;Y_list[[5]]=yi_temp_t_heter;Y_list[[6]]=yi_temp_chisq_heter
names(Y_list)=c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")


library(fda)
basis_need=fourier_basis=create.fourier.basis(c(0,1),10)# basis function
#smoothing 
sample_t=seq(0,1,0.01)#sampling time points
K_seq=2:4
true_label=c(rep(1,100),rep(2,100))
var_ratio=0.9  
rounds=110
burning_period=10
lambda=1
ncomp_l=2

simulation1_res=simulation_results_function(X_list =xij_list,
                             Y=Y_list,
                             basis=basis_need,
                             sample_t=sample_t,
                             var_ratio=var_ratio,
                             K_max=5,
                             true_label=true_label,
                             rounds=rounds,
                             burning_period=burning_period,
                             lambda = lambda,
                             method=method,
                             ncomp_u=10,ncomp_l=ncomp_l,seed=seed_seq,type = type)
save(simulation1_res,file = paste("C:/users/spenc/desktop/simulation_results/new/sim1/ls/s1_",method,seed_seq,".RData",sep = ""))
print(seed_seq)
}


```




```{r}
num_cores=10
library(parallel)
cl=makeCluster(num_cores)
clusterExport(cl,  envir = environment(),varlist =c("color_seq"))
parLapply(cl,51:60,parallel_simulation1,method="ls",type=c(TRUE,TRUE))
parLapply(cl,1:100,parallel_simulation1,method="lad",type=c(FALSE,TRUE))
parLapply(cl,111:120,parallel_simulation1,method="hl",type=c(FALSE,TRUE))

```

结果的调取
```{r}
library(fda)
temp_dir_path=c("C:/users/spenc/desktop/simulation_results/new/sim1/ls",
                "C:/users/spenc/desktop/simulation_results/new/sim1/hl",
                "C:/users/spenc/desktop/simulation_results/new/sim1/lad",
                "C:/users/spenc/desktop/simulation_results/new/sim1/lad_gibbs")
dir_type=c("LS","HL","LAD","LAD_Gibbs")
for (tt in 1:4) 
{

temp_dir=dir(temp_dir_path[tt])
file_num=length(temp_dir)
fun_1=function(t){return(sin((pi*t))*(2^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t))*(2^0.5))}#basis fun 2

real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2))

real_label=c(rep(1,100),rep(2,100))

empty_assessment_BIC=matrix(rep(0,12*3),ncol = 3)
empty_assessment_eBIC=matrix(rep(0,12*3),ncol = 3)
empty_k_BIC=rep(0,12)
empty_k_eBIC=rep(0,12)
empty_mse_BIC=c(list(rep(0,6)),list(rep(0,6)))#空的mse
empty_mse_eBIC=c(list(rep(0,6)),list(rep(0,6)))#空的mse


for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path[tt],temp_dir[i],sep = "/"))
  temp_res=simulation1_res
  
  empty_assessment_BIC=matrix(as.numeric(temp_res$assement_all_mat_BIC),ncol = 3)+empty_assessment_BIC
  empty_k_BIC=empty_k_BIC+temp_res$selected_K_2021_BIC
  empty_assessment_eBIC=matrix(as.numeric(temp_res$assement_all_mat_eBIC),ncol = 3)+empty_assessment_eBIC
  empty_k_eBIC=empty_k_eBIC+temp_res$selected_K_2021_eBIC

 
  #j=1  gibbs; j=2  2021
  j_seq=1:2
  if(tt%in%c(2:3)){j_seq=c(2)}
  for (j in j_seq) 
  {
  empty_error_temp_file_BIC=matrix(rep(0,1200),nrow = 6)#空的mse 当前文件
  empty_error_temp_file_eBIC=matrix(rep(0,1200),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label_BIC=as.numeric(temp_res[[j]][[l]]$selected_res_BIC$labels[[1]])
      temp_label_eBIC=as.numeric(temp_res[[j]][[l]]$selected_res_eBIC$labels[[1]])
      N=length(temp_label_BIC)
      temp_fd_list_BIC=temp_res[[j]][[l]]$selected_res_BIC$beta_fd[[1]]
      temp_fd_list_eBIC=temp_res[[j]][[l]]$selected_res_eBIC$beta_fd[[1]]
      temp_k_selected_BIC=temp_res$selected_K_2021_BIC[(j-1)*6+l]
      temp_k_selected_eBIC=temp_res$selected_K_2021_eBIC[(j-1)*6+l]
      temp_se_seq_BIC=NULL
      temp_se_seq_eBIC=NULL

      for (sample_index in 1:N) 
      {
        beta_fun_BIC=function(x){return(eval.fd(x,temp_fd_list_BIC[[temp_label_BIC[sample_index]]]))}
        beta_fun_eBIC=function(x){return(eval.fd(x,temp_fd_list_eBIC[[temp_label_eBIC[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se_BIC=integrate(function(x){return((beta_fun_BIC(x)-temp_real_beta(x))^2)},0,1)$value
        temp_se_eBIC=integrate(function(x){return((beta_fun_eBIC(x)-temp_real_beta(x))^2)},0,1)$value
        temp_se_seq_BIC=c(temp_se_seq_BIC,temp_se_BIC)
        temp_se_seq_eBIC=c(temp_se_seq_eBIC,temp_se_eBIC)
      }
      empty_error_temp_file_BIC[l,]=temp_se_seq_BIC
      empty_error_temp_file_eBIC[l,]=temp_se_seq_eBIC
    }
     temp_mse_BIC=apply(empty_error_temp_file_BIC,1,mean)
     temp_mse_eBIC=apply(empty_error_temp_file_eBIC,1,mean)
     empty_mse_BIC[[j]]=empty_mse_BIC[[j]]+temp_mse_BIC
     empty_mse_eBIC[[j]]=empty_mse_eBIC[[j]]+temp_mse_eBIC
  }
}
  rownames(empty_assessment_BIC)=paste(rownames(temp_res$assement_all_mat_BIC),"BIC",sep = "_")
  rownames(empty_assessment_eBIC)=paste(rownames(temp_res$assement_all_mat_eBIC),"BIC",sep = "_")
  colnames(empty_assessment_BIC)=paste(colnames(temp_res$assement_all_mat_BIC),"BIC",sep = "_")
  colnames(empty_assessment_eBIC)=paste(colnames(temp_res$assement_all_mat_eBIC),"BIC",sep = "_")


res_k_BIC=empty_k_BIC/length(temp_dir)
res_k_eBIC=empty_k_eBIC/length(temp_dir)
res_assement_BIC=empty_assessment_BIC/length(temp_dir)
res_assement_eBIC=empty_assessment_eBIC/length(temp_dir)
res_mse_gibbs_BIC=empty_mse_BIC[[1]]/length(temp_dir)
res_mse_gibbs_eBIC=empty_mse_eBIC[[1]]/length(temp_dir)
res_mse_2021_BIC=empty_mse_BIC[[2]]/length(temp_dir)
res_mse_2021_eBIC=empty_mse_eBIC[[2]]/length(temp_dir)

res_assement_reorder=rbind(res_assement_BIC[(1:6)*2-1,],res_assement_BIC[(1:6)*2,],
                           res_assement_eBIC[(1:6)*2-1,],res_assement_eBIC[(1:6)*2,])
res_all_df=data.frame(cbind(res_assement_reorder,k=c(res_k_BIC,res_k_eBIC),mse=c(res_mse_gibbs_BIC,res_mse_2021_BIC,res_mse_gibbs_eBIC,res_mse_2021_eBIC)))
rownames(res_all_df)=paste(c("homo-n-gibbs","homo-t-gibbs","homo-chisq-gibbs",
                       "heter-n-gibbs","heter-t-gibbs","heter-chisq-gibbs",
                       "homo-n-2021","homo-t-2021","homo-chisq-2021",
                       "heter-n-2021","heter-t-2021","heter-chisq-2021"),rep(c("BIC","eBIC"),each=12),sep = "-")
res_all_df=data.frame(matrix(unlist(strsplit(rownames(res_all_df),"-")),byrow = T,nrow = nrow(res_all_df)),res_all_df)
colnames(res_all_df)=c("heter_homo","error","method","IC","ARI","RI","NMI","K","MSE")

write.csv(res_all_df,paste("C:/users/spenc/desktop/simulation_results/new/sample1_",dir_type[tt],".csv",sep=""))
  
}
```



## hl  
```{r}
parallel_simulation1_hl=function(seed_seq)
{
  library(FdaCluReg)
set.seed(seed_seq)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2

function_list=list(fun_1,fun_2)#function list
sample_t=seq(0,10,0.1)#sampling time 
group_scale=c(100,100)#group scales
N=sum(group_scale)#number of samples
fda_coef_df=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df_list=list(fda_coef_df)# for multi variables
error_sd=0.2#standard error of observation error 

# generating X  
xij_temp=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df,sample_t=sample_t,error_sd = 0.2,seed = seed_seq)
xij_list=list(xij_temp)

## generating Y
###parameter setting  
#
N=nrow(fda_coef_df)#sample size
reg_error1=rnorm(N,0,1)*0.2#epsilon-1
reg_error2=rt(N,3)*0.2#epsilon-2
reg_error3=(rchisq(N,3)-3)*0.2#epsilon-3
#
reg_var1=rep(1,N)#sigma-1
reg_var2=0.5*fda_coef_df[,1]+0.4*fda_coef_df[,2]#sigma-2
#
reg_coef_df=matrix(c(rep(1,N),rep(1,N/2),rep(-1,N/2)),ncol = 2)
reg_coef_df_list=list(reg_coef_df)#for multi variables
reg_intercept=rep(0,200)


##########################
yi_temp_n_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error1,seed = seed_seq)
yi_temp_t_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error2,seed = seed_seq)
yi_temp_chisq_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error3,seed = seed_seq)


########################
yi_temp_n_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error1,seed = seed_seq)
yi_temp_t_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error2,seed = seed_seq)
yi_temp_chisq_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error3,seed = seed_seq)

Y_list=vector("list",6);
Y_list[[1]]=yi_temp_n_homo;Y_list[[2]]=yi_temp_t_homo;Y_list[[3]]=yi_temp_chisq_homo
Y_list[[4]]=yi_temp_n_heter;Y_list[[5]]=yi_temp_t_heter;Y_list[[6]]=yi_temp_chisq_heter
names(Y_list)=c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")


library(fda)
basis_need=fourier_basis=create.fourier.basis(c(0,10),10)# basis function
#smoothing 
sample_t=seq(0,10,0.1)#sampling time points
K_seq=2:4
true_label=c(rep(1,100),rep(2,100))
var_ratio=0.9
rounds=40
burning_period=5
lambda=1
ncomp_l=1

simulation1_res_ls=simulation_results_function(X_list =xij_list,
                             Y=Y_list,
                             basis=basis_need,
                             sample_t=sample_t,
                             var_ratio=var_ratio,
                             K_max=4,
                             true_label=true_label,
                             rounds=rounds,
                             burning_period=burning_period,
                             lambda = lambda,
                             method="ls",
                             ncomp_u=10,ncomp_l=ncomp_l,seed=seed_seq,type = c(F,T))
save(simulation1_res_ls,file = paste("C:/users/spenc/desktop/simulation_results/simulation1/hl/s1_round_par_",seed_seq,".RData",sep = ""))
print(seed_seq)
}

```

## lad
```{r}
parallel_simulation1_lad=function(seed_seq)
{
  library(FdaCluReg)
set.seed(seed_seq)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2

function_list=list(fun_1,fun_2)#function list
sample_t=seq(0,10,0.1)#sampling time 
group_scale=c(100,100)#group scales
N=sum(group_scale)#number of samples
fda_coef_df=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df_list=list(fda_coef_df)# for multi variables
error_sd=0.2#standard error of observation error 

# generating X  
xij_temp=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df,sample_t=sample_t,error_sd = 0.2,seed = seed_seq)
xij_list=list(xij_temp)

## generating Y
###parameter setting  
#
N=nrow(fda_coef_df)#sample size
reg_error1=rnorm(N,0,1)*0.2#epsilon-1
reg_error2=rt(N,3)*0.2#epsilon-2
reg_error3=(rchisq(N,3)-3)*0.2#epsilon-3
#
reg_var1=rep(1,N)#sigma-1
reg_var2=0.5*fda_coef_df[,1]+0.4*fda_coef_df[,2]#sigma-2
#
reg_coef_df=matrix(c(rep(1,N),rep(1,N/2),rep(-1,N/2)),ncol = 2)
reg_coef_df_list=list(reg_coef_df)#for multi variables
reg_intercept=rep(0,200)


##########################
yi_temp_n_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error1,seed = seed_seq)
yi_temp_t_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error2,seed = seed_seq)
yi_temp_chisq_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error3,seed = seed_seq)


########################
yi_temp_n_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error1,seed = seed_seq)
yi_temp_t_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error2,seed = seed_seq)
yi_temp_chisq_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error3,seed = seed_seq)

Y_list=vector("list",6);
Y_list[[1]]=yi_temp_n_homo;Y_list[[2]]=yi_temp_t_homo;Y_list[[3]]=yi_temp_chisq_homo
Y_list[[4]]=yi_temp_n_heter;Y_list[[5]]=yi_temp_t_heter;Y_list[[6]]=yi_temp_chisq_heter
names(Y_list)=c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")


library(fda)
basis_need=fourier_basis=create.fourier.basis(c(0,10),10)# basis function
#smoothing 
sample_t=seq(0,10,0.1)#sampling time points
K_seq=2:4
true_label=c(rep(1,100),rep(2,100))
var_ratio=0.9
rounds=60
burning_period=5
lambda=0.1
ncomp_l=1

simulation1_res_ls=simulation_results_function(X_list =xij_list,
                             Y=Y_list,
                             basis=basis_need,
                             sample_t=sample_t,
                             var_ratio=var_ratio,
                             K_max=4,
                             true_label=true_label,
                             rounds=rounds,
                             burning_period=burning_period,
                             lambda = lambda,
                             method="lad",
                             ncomp_u=10,ncomp_l=ncomp_l,seed=seed_seq,type = c(F,T))
save(simulation1_res_ls,file = paste("C:/users/spenc/desktop/simulation_results/simulation1/lad/s1_round_par_",seed_seq,".RData",sep = ""))
print(seed_seq)
}

```



```{r}
num_cores=10
library(parallel)
cl=makeCluster(num_cores)
clusterExport(cl,  envir = environment(),varlist =c("color_seq", "simulation_results_function"))
parLapply(cl,(140:180),parallel_simulation1_hl)
#parLapply(cl,1:120,parallel_simulation1_lad)
```
hl结果整理 
```{r}
library(fda)
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation1/hl"
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2

real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2))

real_label=c(rep(1,100),rep(2,100))

empty_assessment=matrix(rep(0,12*3),ncol = 3)
empty_k=rep(0,12)
empty_mse=c(list(rep(0,6)),list(rep(0,6)))#空的mse

for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation1_res_ls
  empty_assessment=matrix(as.numeric(temp_res$assement_all_mat),ncol = 3)+empty_assessment
  empty_k=empty_k+temp_res$selected_K
 
  #j=1  gibbs; j=2  2021
  for (j in 2) 
  {
  empty_error_temp_file=matrix(rep(0,1200),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse[[j]]=empty_mse[[j]]+temp_mse
  }
}

res_k=empty_k/length(temp_dir)
res_assement=empty_assessment/length(temp_dir)
res_mse_gibbs=empty_mse[[1]]/length(temp_dir)
res_mse_2021=empty_mse[[2]]/length(temp_dir)

res_assement_reorder=rbind(res_assement[(1:6)*2-1,],res_assement[(1:6)*2,])
res_all_df=data.frame(cbind(res_assement_reorder,res_k,c(res_mse_gibbs,res_mse_2021)))
rownames(res_all_df)=c("gibbs-homo-n","gibbs-homo-t","gibbs-homo-chisq",
                       "gibbs-heter-n","gibbs-heter-t","gibbs-heter-chisq",
                       "2021-homo-n","2021-homo-t","2021-homo-chisq",
                       "2021-heter-n","2021-heter-t","2021-heter-chisq")
colnames(res_all_df)=c("ARI","RI","NMI","K","MSE")

res_all_df=res_all_df[c(1,7,2,8,3,9,4,10,5,11,6,12),]

write.csv(res_all_df,"C:/users/spenc/desktop/simulation_results/sample1_hl0630.csv")
```


```{r}
num_cores=10
library(parallel)
cl=makeCluster(num_cores)
clusterExport(cl,  envir = environment(),varlist =c("color_seq", "simulation_results_function"))
parLapply(cl,1:100,parallel_simulation1_lad)
1
```
```{r}
library(fda)
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation1/lad"
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2

real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2))

real_label=c(rep(1,100),rep(2,100))

empty_assessment=matrix(rep(0,12*3),ncol = 3)
empty_k=rep(0,12)
empty_mse=c(list(rep(0,6)),list(rep(0,6)))#空的mse

for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation1_res_ls
  empty_assessment=matrix(as.numeric(temp_res$assement_all_mat),ncol = 3)+empty_assessment
  empty_k=empty_k+temp_res$selected_K
 
  #j=1  gibbs; j=2  2021
  for (j in 2) 
  {
  empty_error_temp_file=matrix(rep(0,1200),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse[[j]]=empty_mse[[j]]+temp_mse
  }
}

res_k=empty_k/length(temp_dir)
res_assement=empty_assessment/length(temp_dir)
res_mse_gibbs=empty_mse[[1]]/length(temp_dir)
res_mse_2021=empty_mse[[2]]/length(temp_dir)

res_assement_reorder=rbind(res_assement[(1:6)*2-1,],res_assement[(1:6)*2,])
res_all_df=data.frame(cbind(res_assement_reorder,res_k,c(res_mse_gibbs,res_mse_2021)))
rownames(res_all_df)=c("gibbs-homo-n","gibbs-homo-t","gibbs-homo-chisq",
                       "gibbs-heter-n","gibbs-heter-t","gibbs-heter-chisq",
                       "2021-homo-n","2021-homo-t","2021-homo-chisq",
                       "2021-heter-n","2021-heter-t","2021-heter-chisq")
colnames(res_all_df)=c("ARI","RI","NMI","K","MSE")

res_all_df=res_all_df[c(1,7,2,8,3,9,4,10,5,11,6,12),]

write.csv(res_all_df,"C:/users/spenc/desktop/simulation_results/sample1_lad0630.csv")
```






# simulation 2 
```{r}
parallel_simulation2_ls=function(seed_seq)
{set.seed(seed_seq)
  library(FdaCluReg)
fun_1=function(t){return(sin((pi*t/10))/5^0.5)}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/5^0.5)}#basis fun 2
function_list=list(fun_1,fun_2)#function list
sample_t=seq(0,10,0.1)#sampling time 
group_scale=c(100,100,100)#group scales
N=sum(group_scale)#number of samples
fda_coef_df=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df_list=list(fda_coef_df)
error_sd=0.2#standard error of observation error 
# generating X  
xij_temp=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df,sample_t=sample_t,error_sd = 0.2)
xij_list=list(xij_temp)

## generating Y
###parameter setting  
#
set.seed(1)
#
N=nrow(fda_coef_df)#sample size 
reg_error1=rnorm(N,0,1)*0.2#epsilon-1
reg_error2=rt(N,3)*0.2#epsilon-2
reg_error3=(rchisq(N,3)-3)*0.2#epsilon-3
#
reg_var1=rep(1,N)#sigma-1
reg_var2=0.5*fda_coef_df[,1]+0.4*fda_coef_df[,2]#sigma-2
#
reg_coef_df=as.matrix(cbind(c(rep(1,200),rep(-1,100)),c(rep(1,100),rep(-1,200))))
reg_coef_df_list=list(reg_coef_df)#for multi variables
reg_intercept=c(rep(3,100),rep(-3,100),rep(0,100))

##########################
yi_temp_n_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error1)
yi_temp_t_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error2)
yi_temp_chisq_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error3)


########################
yi_temp_n_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error1)
yi_temp_t_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error2)
yi_temp_chisq_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error3)

Y_list=vector("list",6);
Y_list[[1]]=yi_temp_n_homo
Y_list[[2]]=yi_temp_t_homo
Y_list[[3]]=yi_temp_chisq_homo
Y_list[[4]]=yi_temp_n_heter
Y_list[[5]]=yi_temp_t_heter
Y_list[[6]]=yi_temp_chisq_heter
names(Y_list)=c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")


library(fda)
basis_need=fourier_basis=create.fourier.basis(c(0,10),10)# basis function
#smoothing 
sample_t=seq(0,10,0.1)#sampling time points
K_seq=2:5
true_label=rep(1:3,each=100)
var_ratio=0.9
rounds=100
burning_period=20
lambda=0.2
ncomp_l=1

simulation2_res_ls=simulation_results_function(X_list =xij_list,
                             Y=Y_list,
                             basis=basis_need,
                             sample_t=sample_t,
                             var_ratio=var_ratio,
                             K_max=5,
                             true_label=true_label,
                             rounds=rounds,
                             burning_period=burning_period,
                             lambda = lambda,
                             method="ls",
                             ncomp_u=10,ncomp_l=ncomp_l,seed=seed_seq,type = c(T,T))
save(simulation2_res_ls,file = paste("C:/users/spenc/desktop/simulation_results/simulation2/ls/s2_round_par_",seed_seq,".RData",sep = ""))
print(seed_seq)
}

```


```{r}
library(fda)
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation2/ls/r100l0.2"
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=100)
N=length(real_label)

empty_assessment=matrix(rep(0,12*3),ncol = 3)
empty_k=rep(0,12)
empty_mse=c(list(rep(0,6)),list(rep(0,6)))#空的mse

for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_ls
  empty_assessment=matrix(as.numeric(temp_res$assement_all_mat),ncol = 3)+empty_assessment
  empty_k=empty_k+temp_res$selected_K
  print(temp_res$selected_K)
  #print(temp_res$assement_all_mat)
 
  #j=1  gibbs; j=2  2021
  for (j in 1:2) 
  {
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse[[j]]=empty_mse[[j]]+temp_mse
  }
}

res_k=empty_k/length(temp_dir)
res_assement=empty_assessment/length(temp_dir)
res_mse_gibbs=empty_mse[[1]]/length(temp_dir)
res_mse_2021=empty_mse[[2]]/length(temp_dir)

res_assement_reorder=rbind(res_assement[(1:6)*2-1,],res_assement[(1:6)*2,])
res_all_df=data.frame(cbind(res_assement_reorder,res_k,c(res_mse_gibbs,res_mse_2021)))
rownames(res_all_df)=c("gibbs-homo-n","gibbs-homo-t","gibbs-homo-chisq",
                       "gibbs-heter-n","gibbs-heter-t","gibbs-heter-chisq",
                       "2021-homo-n","2021-homo-t","2021-homo-chisq",
                       "2021-heter-n","2021-heter-t","2021-heter-chisq")
colnames(res_all_df)=c("ARI","RI","NMI","K","MSE")

res_all_df=res_all_df[c(1,7,2,8,3,9,4,10,5,11,6,12),]

write.csv(res_all_df,"C:/users/spenc/desktop/simulation_results/sample2_ls.csv")
```




```{r}
num_cores=10
library(parallel)
cl=makeCluster(num_cores)
clusterExport(cl,  envir = environment(),varlist =c("color_seq", "simulation_results_function"))
rm_index=c(1+seq(0,90,10),2+seq(0,90,10))
parLapply(cl,(101:200)[-rm_index],parallel_simulation2_ls)
1
```

```{r}
parallel_simulation2_hl=function(seed_seq)
{set.seed(seed_seq)
  library(FdaCluReg)
fun_1=function(t){return(sin((pi*t/10))/5^0.5)}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/5^0.5)}#basis fun 2
function_list=list(fun_1,fun_2)#function list
sample_t=seq(0,10,0.1)#sampling time 
group_scale=c(100,100,100)#group scales
N=sum(group_scale)#number of samples
fda_coef_df=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df_list=list(fda_coef_df)
error_sd=0.2#standard error of observation error 
# generating X  
xij_temp=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df,sample_t=sample_t,error_sd = 0.2)
xij_list=list(xij_temp)

## generating Y
###parameter setting  
#
set.seed(1)
#
N=nrow(fda_coef_df)#sample size 
reg_error1=rnorm(N,0,1)*0.2#epsilon-1
reg_error2=rt(N,3)*0.2#epsilon-2
reg_error3=(rchisq(N,3)-3)*0.2#epsilon-3
#
reg_var1=rep(1,N)#sigma-1
reg_var2=0.5*fda_coef_df[,1]+0.4*fda_coef_df[,2]#sigma-2
#
reg_coef_df=as.matrix(cbind(c(rep(1,200),rep(-1,100)),c(rep(1,100),rep(-1,200))))
reg_coef_df_list=list(reg_coef_df)#for multi variables
reg_intercept=c(rep(3,100),rep(-3,100),rep(0,100))

##########################
yi_temp_n_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error1)
yi_temp_t_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error2)
yi_temp_chisq_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error3)


########################
yi_temp_n_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error1)
yi_temp_t_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error2)
yi_temp_chisq_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error3)

Y_list=vector("list",6);
Y_list[[1]]=yi_temp_n_homo
Y_list[[2]]=yi_temp_t_homo
Y_list[[3]]=yi_temp_chisq_homo
Y_list[[4]]=yi_temp_n_heter
Y_list[[5]]=yi_temp_t_heter
Y_list[[6]]=yi_temp_chisq_heter
names(Y_list)=c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")


library(fda)
basis_need=fourier_basis=create.fourier.basis(c(0,10),10)# basis function
#smoothing 
sample_t=seq(0,10,0.1)#sampling time points
K_seq=2:5
true_label=rep(1:3,each=100)
var_ratio=0.9
rounds=100
burning_period=20
lambda=0.2
ncomp_l=1

simulation2_res_hl=simulation_results_function(X_list =xij_list,
                             Y=Y_list,
                             basis=basis_need,
                             sample_t=sample_t,
                             var_ratio=var_ratio,
                             K_max=5,
                             true_label=true_label,
                             rounds=rounds,
                             burning_period=burning_period,
                             lambda = lambda,
                             method="hl",
                             ncomp_u=10,ncomp_l=ncomp_l,seed=seed_seq,type = c(F,T))
save(simulation2_res_hl,file = paste("C:/users/spenc/desktop/simulation_results/simulation2/hl/s2_round_par_",seed_seq,".RData",sep = ""))
print(seed_seq)
}

```

```{r}
parallel_simulation2_lad=function(seed_seq)
{set.seed(seed_seq)
  library(FdaCluReg)
fun_1=function(t){return(sin((pi*t/10))/5^0.5)}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/5^0.5)}#basis fun 2
function_list=list(fun_1,fun_2)#function list
sample_t=seq(0,10,0.1)#sampling time 
group_scale=c(100,100,100)#group scales
N=sum(group_scale)#number of samples
fda_coef_df=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df_list=list(fda_coef_df)
error_sd=0.2#standard error of observation error 
# generating X  
xij_temp=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df,sample_t=sample_t,error_sd = 0.2)
xij_list=list(xij_temp)

## generating Y
###parameter setting  
#
set.seed(1)
#
N=nrow(fda_coef_df)#sample size 
reg_error1=rnorm(N,0,1)*0.2#epsilon-1
reg_error2=rt(N,3)*0.2#epsilon-2
reg_error3=(rchisq(N,3)-3)*0.2#epsilon-3
#
reg_var1=rep(1,N)#sigma-1
reg_var2=0.5*fda_coef_df[,1]+0.4*fda_coef_df[,2]#sigma-2
#
reg_coef_df=as.matrix(cbind(c(rep(1,200),rep(-1,100)),c(rep(1,100),rep(-1,200))))
reg_coef_df_list=list(reg_coef_df)#for multi variables
reg_intercept=c(rep(3,100),rep(-3,100),rep(0,100))

##########################
yi_temp_n_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error1)
yi_temp_t_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error2)
yi_temp_chisq_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error3)


########################
yi_temp_n_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error1)
yi_temp_t_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error2)
yi_temp_chisq_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error3)

Y_list=vector("list",6);
Y_list[[1]]=yi_temp_n_homo
Y_list[[2]]=yi_temp_t_homo
Y_list[[3]]=yi_temp_chisq_homo
Y_list[[4]]=yi_temp_n_heter
Y_list[[5]]=yi_temp_t_heter
Y_list[[6]]=yi_temp_chisq_heter
names(Y_list)=c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")


library(fda)
basis_need=fourier_basis=create.fourier.basis(c(0,10),10)# basis function
#smoothing 
sample_t=seq(0,10,0.1)#sampling time points
K_seq=2:5
true_label=rep(1:3,each=100)
var_ratio=0.9
rounds=100
burning_period=20
lambda=0.2
ncomp_l=1

simulation2_res_lad=simulation_results_function(X_list =xij_list,
                             Y=Y_list,
                             basis=basis_need,
                             sample_t=sample_t,
                             var_ratio=var_ratio,
                             K_max=5,
                             true_label=true_label,
                             rounds=rounds,
                             burning_period=burning_period,
                             lambda = lambda,
                             method="lad",
                             ncomp_u=10,ncomp_l=ncomp_l,seed=seed_seq,type = c(F,T))
save(simulation2_res_lad,file = paste("C:/users/spenc/desktop/simulation_results/simulation2/lad/s2_round_par_",seed_seq,".RData",sep = ""))
print(seed_seq)
}

```

```{r}
library(fda)
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation2/hl"
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=100)
N=length(real_label)

empty_assessment=matrix(rep(0,12*3),ncol = 3)
empty_k=rep(0,12)
empty_mse=c(list(rep(0,6)),list(rep(0,6)))#空的mse

for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_hl
  empty_assessment=matrix(as.numeric(temp_res$assement_all_mat),ncol = 3)+empty_assessment
  empty_k=empty_k+temp_res$selected_K
  print(temp_res$selected_K)
  #print(temp_res$assement_all_mat)
 
  #j=1  gibbs; j=2  2021
  for (j in 2) 
  {
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse[[j]]=empty_mse[[j]]+temp_mse
  }
}

res_k=empty_k/length(temp_dir)
res_assement=empty_assessment/length(temp_dir)
res_mse_gibbs=empty_mse[[1]]/length(temp_dir)
res_mse_2021=empty_mse[[2]]/length(temp_dir)

res_assement_reorder=rbind(res_assement[(1:6)*2-1,],res_assement[(1:6)*2,])
res_all_df=data.frame(cbind(res_assement_reorder,res_k,c(res_mse_gibbs,res_mse_2021)))
rownames(res_all_df)=c("gibbs-homo-n","gibbs-homo-t","gibbs-homo-chisq",
                       "gibbs-heter-n","gibbs-heter-t","gibbs-heter-chisq",
                       "2021-homo-n","2021-homo-t","2021-homo-chisq",
                       "2021-heter-n","2021-heter-t","2021-heter-chisq")
colnames(res_all_df)=c("ARI","RI","NMI","K","MSE")

res_all_df=res_all_df[c(1,7,2,8,3,9,4,10,5,11,6,12),]

write.csv(res_all_df,"C:/users/spenc/desktop/simulation_results/sample2_hl.csv")
```


```{r}
library(fda)
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation2/lad"
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=100)
N=length(real_label)

empty_assessment=matrix(rep(0,12*3),ncol = 3)
empty_k=rep(0,12)
empty_mse=c(list(rep(0,6)),list(rep(0,6)))#空的mse

for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_lad
  empty_assessment=matrix(as.numeric(temp_res$assement_all_mat),ncol = 3)+empty_assessment
  empty_k=empty_k+temp_res$selected_K
  print(temp_res$selected_K)
  #print(temp_res$assement_all_mat)
 
  #j=1  gibbs; j=2  2021
  for (j in 2) 
  {
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse[[j]]=empty_mse[[j]]+temp_mse
  }
}

res_k=empty_k/length(temp_dir)
res_assement=empty_assessment/length(temp_dir)
res_mse_gibbs=empty_mse[[1]]/length(temp_dir)
res_mse_2021=empty_mse[[2]]/length(temp_dir)

res_assement_reorder=rbind(res_assement[(1:6)*2-1,],res_assement[(1:6)*2,])
res_all_df=data.frame(cbind(res_assement_reorder,res_k,c(res_mse_gibbs,res_mse_2021)))
rownames(res_all_df)=c("gibbs-homo-n","gibbs-homo-t","gibbs-homo-chisq",
                       "gibbs-heter-n","gibbs-heter-t","gibbs-heter-chisq",
                       "2021-homo-n","2021-homo-t","2021-homo-chisq",
                       "2021-heter-n","2021-heter-t","2021-heter-chisq")
colnames(res_all_df)=c("ARI","RI","NMI","K","MSE")

res_all_df=res_all_df[c(1,7,2,8,3,9,4,10,5,11,6,12),]

write.csv(res_all_df,"C:/users/spenc/desktop/simulation_results/sample2_lad.csv")
```


```{r}
num_cores=10
library(parallel)
cl=makeCluster(num_cores)
clusterExport(cl,  envir = environment(),varlist =c("color_seq", "simulation_results_function"))
#rm_index=c(1+seq(0,90,10),2+seq(0,90,10))
parLapply(cl,(1:50),parallel_simulation2_hl)
1
```

```{r}
num_cores=10
library(parallel)
cl=makeCluster(num_cores)
clusterExport(cl,  envir = environment(),varlist =c("color_seq", "simulation_results_function"))
#rm_index=c(1+seq(0,90,10),2+seq(0,90,10))
parLapply(cl,(1:150),parallel_simulation2_lad)
```

# simulation 3 
```{r}
parallel_simulation3_ls=function(seed_seq)
{set.seed(seed_seq)
  library(FdaCluReg)
fun_1=function(t){return(sin((pi*t/10))/5^0.5)}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/5^0.5)}#basis fun 2
function_list=list(fun_1,fun_2)#function list
sample_t=seq(0,10,0.1)#sampling time 
group_scale=c(100,100,100)#group scales
N=sum(group_scale)#number of samples
fda_coef_df_list=NULL
fda_coef_df1=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df2=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df_list=list(fda_coef_df1,fda_coef_df2)#for multi variables
error_sd=0.2#standard error of observation error 
xij_temp_1=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df1,sample_t=sample_t,error_sd = 0.2)
xij_temp_2=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df2,sample_t=sample_t,error_sd = 0.2)

xij_list=list(xij_temp_1,xij_temp_2)#for multi variables

## generating Y
###parameter setting  
#
reg_error1=rnorm(N,0,1)*0.2#epsilon-1
reg_error2=rt(N,3)*0.2#epsilon-2
reg_error3=(rchisq(N,3)-3)*0.2#epsilon-3
#
reg_var1=rep(1,N)#sigma-1
reg_var2=0.5*fda_coef_df1[,1]+0.4*fda_coef_df1[,2]+0.5*fda_coef_df2[,1]+0.4*fda_coef_df2[,2]#sigma-2
#
reg_coef_df_list=NULL
reg_coef_df_var1=as.matrix(cbind(c(rep(1,200),rep(-1,100)),c(rep(1,100),rep(-1,200))))
reg_coef_df_var2=as.matrix(cbind(c(rep(1,200),rep(-0.5,100)),c(rep(0.5,100),rep(-0.5,100),rep(-1,100))))
reg_coef_df_list=list(reg_coef_df_var1,reg_coef_df_var2)#for multi variables
reg_intercept=c(rep(3,100),rep(-3,100),rep(0,100))

yi_temp_n_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error1)
yi_temp_t_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error2)
yi_temp_chisq_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error3)


########################
yi_temp_n_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error1)
yi_temp_t_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error2)
yi_temp_chisq_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error3)

Y_list=vector("list",6);
Y_list[[1]]=yi_temp_n_homo
Y_list[[2]]=yi_temp_t_homo
Y_list[[3]]=yi_temp_chisq_homo
Y_list[[4]]=yi_temp_n_heter
Y_list[[5]]=yi_temp_t_heter
Y_list[[6]]=yi_temp_chisq_heter
names(Y_list)=c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")



library(fda)
basis_need=fourier_basis=create.fourier.basis(c(0,10),10)# basis function
#smoothing 
sample_t=seq(0,10,0.1)#sampling time points
K_seq=2:5
true_label=rep(1:3,each=100)
var_ratio=0.9
rounds=100
burning_period=20
lambda=0.3
ncomp_l=1

simulation3_res_ls=simulation_results_function(X_list =xij_list,
                             Y=Y_list,
                             basis=basis_need,
                             sample_t=sample_t,
                             var_ratio=var_ratio,
                             K_max=5,
                             true_label=true_label,
                             rounds=rounds,
                             burning_period=burning_period,
                             lambda = lambda,
                             method="ls",
                             ncomp_u=10,ncomp_l=ncomp_l,seed=seed_seq,type = c(T,T))
save(simulation3_res_ls,file = paste("C:/users/spenc/desktop/simulation_results/simulation3/ls/s2_round_par_",seed_seq,".RData",sep = ""))
}
```


```{r}
num_cores=10
library(parallel)
cl=makeCluster(num_cores)
clusterExport(cl,  envir = environment(),varlist =c("color_seq", "simulation_results_function"))
parLapply(cl,(1:110),parallel_simulation3_ls)
```

```{r}
library(fda)
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation3/ls/0701"
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}

real_beta_function2_1=function(x){return(fun_1(x)+0.5*fun_2(x))}
real_beta_function2_2=function(x){return(fun_1(x)-0.5*fun_2(x))}
real_beta_function2_3=function(x){return(-0.5*fun_1(x)-fun_2(x))}

beta_function_list_1=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))
beta_function_list_2=c(list(real_beta_function2_1),list(real_beta_function2_2),list(real_beta_function2_3))
real_label=rep(1:3,each=100)
N=length(real_label)

empty_assessment=matrix(rep(0,12*3),ncol = 3)
empty_k=rep(0,12)
empty_mse1=c(list(rep(0,6)),list(rep(0,6)))#空的mse
empty_mse2=c(list(rep(0,6)),list(rep(0,6)))#空的mse

for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation3_res_ls
  empty_assessment=matrix(as.numeric(temp_res$assement_all_mat),ncol = 3)+empty_assessment
  empty_k=empty_k+temp_res$selected_K
  print(temp_res$selected_K)
  #print(temp_res$assement_all_mat)
 
  #j=1  gibbs; j=2  2021
  for (j in 1:2) 
  {
  empty_error_temp_file1=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
  empty_error_temp_file2=matrix(rep(0,6*N),nrow = 6)
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq1=NULL
      temp_se_seq2=NULL

      for (sample_index in 1:N) 
      {
        beta_fun1=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]][1]))}
        beta_fun2=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]][2]))}
        temp_real_beta1=beta_function_list_1[[real_label[sample_index]]]
        temp_real_beta2=beta_function_list_2[[real_label[sample_index]]]
        temp_se1=integrate(function(x){return((beta_fun1(x)-temp_real_beta1(x))^2)},0,10)$value
        temp_se2=integrate(function(x){return((beta_fun2(x)-temp_real_beta2(x))^2)},0,10)$value
        temp_se_seq1=c(temp_se_seq1,temp_se1)
        temp_se_seq2=c(temp_se_seq2,temp_se2)
      }
      empty_error_temp_file1[l,]=temp_se_seq1
      empty_error_temp_file2[l,]=temp_se_seq2
    }
     temp_mse1=apply(empty_error_temp_file1,1,mean)
     temp_mse2=apply(empty_error_temp_file2,1,mean)
     empty_mse1[[j]]=empty_mse1[[j]]+temp_mse1
     empty_mse2[[j]]=empty_mse2[[j]]+temp_mse2
  }
}

res_k=empty_k/length(temp_dir)
res_assement=empty_assessment/length(temp_dir)
res_mse_gibbs1=empty_mse1[[1]]/length(temp_dir)
res_mse_20211=empty_mse1[[2]]/length(temp_dir)
res_mse_gibbs2=empty_mse2[[1]]/length(temp_dir)
res_mse_20212=empty_mse2[[2]]/length(temp_dir)

res_assement_reorder=rbind(res_assement[(1:6)*2-1,],res_assement[(1:6)*2,])
res_all_df=data.frame(cbind(res_assement_reorder,res_k,c(res_mse_gibbs1,res_mse_20211),c(res_mse_gibbs2,res_mse_20212)))
rownames(res_all_df)=c("gibbs-homo-n","gibbs-homo-t","gibbs-homo-chisq",
                       "gibbs-heter-n","gibbs-heter-t","gibbs-heter-chisq",
                       "2021-homo-n","2021-homo-t","2021-homo-chisq",
                       "2021-heter-n","2021-heter-t","2021-heter-chisq")
colnames(res_all_df)=c("ARI","RI","NMI","K","MSE1","MSE2")

res_all_df=res_all_df[c(1,7,2,8,3,9,4,10,5,11,6,12),]

write.csv(res_all_df,"C:/users/spenc/desktop/simulation_results/sample3_ls0701.csv")
1
```


#HL
```{r}
parallel_simulation3_hl=function(seed_seq)
{set.seed(seed_seq)
  library(FdaCluReg)
fun_1=function(t){return(sin((pi*t/10))/5^0.5)}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/5^0.5)}#basis fun 2
function_list=list(fun_1,fun_2)#function list
sample_t=seq(0,10,0.1)#sampling time 
group_scale=c(100,100,100)#group scales
N=sum(group_scale)#number of samples
fda_coef_df_list=NULL
fda_coef_df1=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df2=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df_list=list(fda_coef_df1,fda_coef_df2)#for multi variables
error_sd=0.2#standard error of observation error 
xij_temp_1=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df1,sample_t=sample_t,error_sd = 0.2)
xij_temp_2=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df2,sample_t=sample_t,error_sd = 0.2)

xij_list=list(xij_temp_1,xij_temp_2)#for multi variables

## generating Y
###parameter setting  
#
reg_error1=rnorm(N,0,1)*0.2#epsilon-1
reg_error2=rt(N,3)*0.2#epsilon-2
reg_error3=(rchisq(N,3)-3)*0.2#epsilon-3
#
reg_var1=rep(1,N)#sigma-1
reg_var2=0.5*fda_coef_df1[,1]+0.4*fda_coef_df1[,2]+0.5*fda_coef_df2[,1]+0.4*fda_coef_df2[,2]#sigma-2
#
reg_coef_df_list=NULL
reg_coef_df_var1=as.matrix(cbind(c(rep(1,200),rep(-1,100)),c(rep(1,100),rep(-1,200))))
reg_coef_df_var2=as.matrix(cbind(c(rep(1,200),rep(-0.5,100)),c(rep(0.5,100),rep(-0.5,100),rep(-1,100))))
reg_coef_df_list=list(reg_coef_df_var1,reg_coef_df_var2)#for multi variables
reg_intercept=c(rep(3,100),rep(-3,100),rep(0,100))

yi_temp_n_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error1)
yi_temp_t_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error2)
yi_temp_chisq_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error3)


########################
yi_temp_n_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error1)
yi_temp_t_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error2)
yi_temp_chisq_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error3)

Y_list=vector("list",6);
Y_list[[1]]=yi_temp_n_homo
Y_list[[2]]=yi_temp_t_homo
Y_list[[3]]=yi_temp_chisq_homo
Y_list[[4]]=yi_temp_n_heter
Y_list[[5]]=yi_temp_t_heter
Y_list[[6]]=yi_temp_chisq_heter
names(Y_list)=c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")



library(fda)
basis_need=fourier_basis=create.fourier.basis(c(0,10),10)# basis function
#smoothing 
sample_t=seq(0,10,0.1)#sampling time points
K_seq=2:5
true_label=rep(1:3,each=100)
var_ratio=0.9
rounds=100
burning_period=20
lambda=0.3
ncomp_l=1

simulation3_res_hl=simulation_results_function(X_list =xij_list,
                             Y=Y_list,
                             basis=basis_need,
                             sample_t=sample_t,
                             var_ratio=var_ratio,
                             K_max=5,
                             true_label=true_label,
                             rounds=rounds,
                             burning_period=burning_period,
                             lambda = lambda,
                             method="hl",
                             ncomp_u=10,ncomp_l=ncomp_l,seed=seed_seq,type = c(F,T))
save(simulation3_res_hl,file = paste("C:/users/spenc/desktop/simulation_results/simulation3/hl/s2_round_par_",seed_seq,".RData",sep = ""))
}
```


```{r}
num_cores=10
library(parallel)
cl=makeCluster(num_cores)
clusterExport(cl,  envir = environment(),varlist =c("color_seq", "simulation_results_function"))
parLapply(cl,(111:130),parallel_simulation3_hl)
```
```{r}
library(fda)
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation3/hl"
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}

real_beta_function2_1=function(x){return(fun_1(x)+0.5*fun_2(x))}
real_beta_function2_2=function(x){return(fun_1(x)-0.5*fun_2(x))}
real_beta_function2_3=function(x){return(-0.5*fun_1(x)-fun_2(x))}

beta_function_list_1=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))
beta_function_list_2=c(list(real_beta_function2_1),list(real_beta_function2_2),list(real_beta_function2_3))
real_label=rep(1:3,each=100)
N=length(real_label)

empty_assessment=matrix(rep(0,12*3),ncol = 3)
empty_k=rep(0,12)
empty_mse1=c(list(rep(0,6)),list(rep(0,6)))#空的mse
empty_mse2=c(list(rep(0,6)),list(rep(0,6)))#空的mse

for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation3_res_hl
  empty_assessment=matrix(as.numeric(temp_res$assement_all_mat),ncol = 3)+empty_assessment
  empty_k=empty_k+temp_res$selected_K
  print(temp_res$selected_K)
  #print(temp_res$assement_all_mat)
 
  #j=1  gibbs; j=2  2021
  for (j in 2) 
  {
  empty_error_temp_file1=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
  empty_error_temp_file2=matrix(rep(0,6*N),nrow = 6)
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq1=NULL
      temp_se_seq2=NULL

      for (sample_index in 1:N) 
      {
        beta_fun1=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]][1]))}
        beta_fun2=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]][2]))}
        temp_real_beta1=beta_function_list_1[[real_label[sample_index]]]
        temp_real_beta2=beta_function_list_2[[real_label[sample_index]]]
        temp_se1=integrate(function(x){return((beta_fun1(x)-temp_real_beta1(x))^2)},0,10)$value
        temp_se2=integrate(function(x){return((beta_fun2(x)-temp_real_beta2(x))^2)},0,10)$value
        temp_se_seq1=c(temp_se_seq1,temp_se1)
        temp_se_seq2=c(temp_se_seq2,temp_se2)
      }
      empty_error_temp_file1[l,]=temp_se_seq1
      empty_error_temp_file2[l,]=temp_se_seq2
    }
     temp_mse1=apply(empty_error_temp_file1,1,mean)
     temp_mse2=apply(empty_error_temp_file2,1,mean)
     empty_mse1[[j]]=empty_mse1[[j]]+temp_mse1
     empty_mse2[[j]]=empty_mse2[[j]]+temp_mse2
  }
}

res_k=empty_k/length(temp_dir)
res_assement=empty_assessment/length(temp_dir)
res_mse_gibbs1=empty_mse1[[1]]/length(temp_dir)
res_mse_20211=empty_mse1[[2]]/length(temp_dir)
res_mse_gibbs2=empty_mse2[[1]]/length(temp_dir)
res_mse_20212=empty_mse2[[2]]/length(temp_dir)

res_assement_reorder=rbind(res_assement[(1:6)*2-1,],res_assement[(1:6)*2,])
res_all_df=data.frame(cbind(res_assement_reorder,res_k,c(res_mse_gibbs1,res_mse_20211),c(res_mse_gibbs2,res_mse_20212)))
rownames(res_all_df)=c("gibbs-homo-n","gibbs-homo-t","gibbs-homo-chisq",
                       "gibbs-heter-n","gibbs-heter-t","gibbs-heter-chisq",
                       "2021-homo-n","2021-homo-t","2021-homo-chisq",
                       "2021-heter-n","2021-heter-t","2021-heter-chisq")
colnames(res_all_df)=c("ARI","RI","NMI","K","MSE1","MSE2")

res_all_df=res_all_df[c(1,7,2,8,3,9,4,10,5,11,6,12),]

write.csv(res_all_df,"C:/users/spenc/desktop/simulation_results/sample3_hl0701.csv")
1
```
#LAD
```{r}
parallel_simulation3_lad=function(seed_seq)
{set.seed(seed_seq)
  library(FdaCluReg)
fun_1=function(t){return(sin((pi*t/10))/5^0.5)}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/5^0.5)}#basis fun 2
function_list=list(fun_1,fun_2)#function list
sample_t=seq(0,10,0.1)#sampling time 
group_scale=c(100,100,100)#group scales
N=sum(group_scale)#number of samples
fda_coef_df_list=NULL
fda_coef_df1=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df2=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df_list=list(fda_coef_df1,fda_coef_df2)#for multi variables
error_sd=0.2#standard error of observation error 
xij_temp_1=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df1,sample_t=sample_t,error_sd = 0.2)
xij_temp_2=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df2,sample_t=sample_t,error_sd = 0.2)

xij_list=list(xij_temp_1,xij_temp_2)#for multi variables

## generating Y
###parameter setting  
#
reg_error1=rnorm(N,0,1)*0.2#epsilon-1
reg_error2=rt(N,3)*0.2#epsilon-2
reg_error3=(rchisq(N,3)-3)*0.2#epsilon-3
#
reg_var1=rep(1,N)#sigma-1
reg_var2=0.5*fda_coef_df1[,1]+0.4*fda_coef_df1[,2]+0.5*fda_coef_df2[,1]+0.4*fda_coef_df2[,2]#sigma-2
#
reg_coef_df_list=NULL
reg_coef_df_var1=as.matrix(cbind(c(rep(1,200),rep(-1,100)),c(rep(1,100),rep(-1,200))))
reg_coef_df_var2=as.matrix(cbind(c(rep(1,200),rep(-0.5,100)),c(rep(0.5,100),rep(-0.5,100),rep(-1,100))))
reg_coef_df_list=list(reg_coef_df_var1,reg_coef_df_var2)#for multi variables
reg_intercept=c(rep(3,100),rep(-3,100),rep(0,100))

yi_temp_n_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error1)
yi_temp_t_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error2)
yi_temp_chisq_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error3)


########################
yi_temp_n_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error1)
yi_temp_t_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error2)
yi_temp_chisq_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error3)

Y_list=vector("list",6);
Y_list[[1]]=yi_temp_n_homo
Y_list[[2]]=yi_temp_t_homo
Y_list[[3]]=yi_temp_chisq_homo
Y_list[[4]]=yi_temp_n_heter
Y_list[[5]]=yi_temp_t_heter
Y_list[[6]]=yi_temp_chisq_heter
names(Y_list)=c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")



library(fda)
basis_need=fourier_basis=create.fourier.basis(c(0,10),10)# basis function
#smoothing 
sample_t=seq(0,10,0.1)#sampling time points
K_seq=2:5
true_label=rep(1:3,each=100)
var_ratio=0.9
rounds=100
burning_period=20
lambda=0.3
ncomp_l=1

simulation3_res_lad=simulation_results_function(X_list =xij_list,
                             Y=Y_list,
                             basis=basis_need,
                             sample_t=sample_t,
                             var_ratio=var_ratio,
                             K_max=5,
                             true_label=true_label,
                             rounds=rounds,
                             burning_period=burning_period,
                             lambda = lambda,
                             method="lad",
                             ncomp_u=10,ncomp_l=ncomp_l,seed=seed_seq,type = c(F,T))
save(simulation3_res_lad,file = paste("C:/users/spenc/desktop/simulation_results/simulation3/lad/s2_round_par_",seed_seq,".RData",sep = ""))
}
```

```{r}
num_cores=10
library(parallel)
cl=makeCluster(num_cores)
clusterExport(cl,  envir = environment(),varlist =c("color_seq", "simulation_results_function"))
parLapply(cl,(1:100),parallel_simulation3_lad)
1
```


```{r}
library(fda)
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation3/lad"
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}

real_beta_function2_1=function(x){return(fun_1(x)+0.5*fun_2(x))}
real_beta_function2_2=function(x){return(fun_1(x)-0.5*fun_2(x))}
real_beta_function2_3=function(x){return(-0.5*fun_1(x)-fun_2(x))}

beta_function_list_1=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))
beta_function_list_2=c(list(real_beta_function2_1),list(real_beta_function2_2),list(real_beta_function2_3))
real_label=rep(1:3,each=100)
N=length(real_label)

empty_assessment=matrix(rep(0,12*3),ncol = 3)
empty_k=rep(0,12)
empty_mse1=c(list(rep(0,6)),list(rep(0,6)))#空的mse
empty_mse2=c(list(rep(0,6)),list(rep(0,6)))#空的mse

for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation3_res_lad
  empty_assessment=matrix(as.numeric(temp_res$assement_all_mat),ncol = 3)+empty_assessment
  empty_k=empty_k+temp_res$selected_K
  print(temp_res$selected_K)
  #print(temp_res$assement_all_mat)
 
  #j=1  gibbs; j=2  2021
  for (j in 2) 
  {
  empty_error_temp_file1=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
  empty_error_temp_file2=matrix(rep(0,6*N),nrow = 6)
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq1=NULL
      temp_se_seq2=NULL

      for (sample_index in 1:N) 
      {
        beta_fun1=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]][1]))}
        beta_fun2=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]][2]))}
        temp_real_beta1=beta_function_list_1[[real_label[sample_index]]]
        temp_real_beta2=beta_function_list_2[[real_label[sample_index]]]
        temp_se1=integrate(function(x){return((beta_fun1(x)-temp_real_beta1(x))^2)},0,10)$value
        temp_se2=integrate(function(x){return((beta_fun2(x)-temp_real_beta2(x))^2)},0,10)$value
        temp_se_seq1=c(temp_se_seq1,temp_se1)
        temp_se_seq2=c(temp_se_seq2,temp_se2)
      }
      empty_error_temp_file1[l,]=temp_se_seq1
      empty_error_temp_file2[l,]=temp_se_seq2
    }
     temp_mse1=apply(empty_error_temp_file1,1,mean)
     temp_mse2=apply(empty_error_temp_file2,1,mean)
     empty_mse1[[j]]=empty_mse1[[j]]+temp_mse1
     empty_mse2[[j]]=empty_mse2[[j]]+temp_mse2
  }
}

res_k=empty_k/length(temp_dir)
res_assement=empty_assessment/length(temp_dir)
res_mse_gibbs1=empty_mse1[[1]]/length(temp_dir)
res_mse_20211=empty_mse1[[2]]/length(temp_dir)
res_mse_gibbs2=empty_mse2[[1]]/length(temp_dir)
res_mse_20212=empty_mse2[[2]]/length(temp_dir)

res_assement_reorder=rbind(res_assement[(1:6)*2-1,],res_assement[(1:6)*2,])
res_all_df=data.frame(cbind(res_assement_reorder,res_k,c(res_mse_gibbs1,res_mse_20211),c(res_mse_gibbs2,res_mse_20212)))
rownames(res_all_df)=c("gibbs-homo-n","gibbs-homo-t","gibbs-homo-chisq",
                       "gibbs-heter-n","gibbs-heter-t","gibbs-heter-chisq",
                       "2021-homo-n","2021-homo-t","2021-homo-chisq",
                       "2021-heter-n","2021-heter-t","2021-heter-chisq")
colnames(res_all_df)=c("ARI","RI","NMI","K","MSE1","MSE2")

res_all_df=res_all_df[c(1,7,2,8,3,9,4,10,5,11,6,12),]

write.csv(res_all_df,"C:/users/spenc/desktop/simulation_results/sample3_lad0701.csv")
1
```
# 样本变化对精度的影响  

```{r}
parallel_simulation2_ls=function(seed_seq,M=1)
{set.seed(seed_seq)
  library(FdaCluReg)
fun_1=function(t){return(sin((pi*t/10))/5^0.5)}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/5^0.5)}#basis fun 2
function_list=list(fun_1,fun_2)#function list
sample_t=seq(0,10,0.1)#sampling time 
group_scale=c(100,100,100)*M#group scales
N=sum(group_scale)#number of samples
fda_coef_df=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df_list=list(fda_coef_df)
error_sd=0.2#standard error of observation error 
# generating X  
xij_temp=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df,sample_t=sample_t,error_sd = 0.2)
xij_list=list(xij_temp)

## generating Y
###parameter setting  
#
set.seed(1)
#
N=nrow(fda_coef_df)#sample size 
reg_error1=rnorm(N,0,1)*0.2#epsilon-1
reg_error2=rt(N,3)*0.2#epsilon-2
reg_error3=(rchisq(N,3)-3)*0.2#epsilon-3
#
reg_var1=rep(1,N)#sigma-1
reg_var2=0.5*fda_coef_df[,1]+0.4*fda_coef_df[,2]#sigma-2
#
reg_coef_df=as.matrix(cbind(c(rep(1,200*M),rep(-1,100*M)),c(rep(1,100*M),rep(-1,200*M))))
reg_coef_df_list=list(reg_coef_df)#for multi variables
reg_intercept=c(rep(3,100*M),rep(-3,100*M),rep(0,100*M))

##########################
yi_temp_n_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error1)
yi_temp_t_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error2)
yi_temp_chisq_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error3)


########################
yi_temp_n_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error1)
yi_temp_t_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error2)
yi_temp_chisq_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error3)

Y_list=vector("list",6);
Y_list[[1]]=yi_temp_n_homo
Y_list[[2]]=yi_temp_t_homo
Y_list[[3]]=yi_temp_chisq_homo
Y_list[[4]]=yi_temp_n_heter
Y_list[[5]]=yi_temp_t_heter
Y_list[[6]]=yi_temp_chisq_heter
names(Y_list)=c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")


library(fda)
basis_need=fourier_basis=create.fourier.basis(c(0,10),10)# basis function
#smoothing 
sample_t=seq(0,10,0.1)#sampling time points
K_seq=2:5
true_label=rep(1:3,each=100*M)
var_ratio=0.9
rounds=100
burning_period=10
lambda=0.2
ncomp_l=1

simulation2_res_ls=simulation_results_function(X_list =xij_list,
                             Y=Y_list,
                             basis=basis_need,
                             sample_t=sample_t,
                             var_ratio=var_ratio,
                             K_max=5,
                             true_label=true_label,
                             rounds=rounds,
                             burning_period=burning_period,
                             lambda = lambda,
                             method="ls",
                             ncomp_u=10,ncomp_l=ncomp_l,seed=seed_seq,type = c(T,T))
save(simulation2_res_ls,file = paste("C:/users/spenc/desktop/simulation_results/simulation4/m30/s4_",M,seed_seq,".RData",sep = ""))
print(seed_seq)
}

```

```{r}
num_cores=10
library(parallel)
cl=makeCluster(num_cores)
clusterExport(cl,  envir = environment(),varlist =c("color_seq", "simulation_results_function"))
parLapply(cl,(101:140),parallel_simulation2_ls,M=3)
```
统计结果--收敛性 1:1:1  
gibbs结果汇总  
```{r}
M=0.5
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation4/m05"
library(fda)
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=M*100)
N=length(real_label)
j=1
empty_mse=NULL
empty_ari=NULL
for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_ls
empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[c(1,3,5,7,9,11),1]))
  #j=1  gibbs; j=2  2021
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse=c(empty_mse,temp_mse)
}


mse_mat=matrix(empty_mse,byrow = T,ncol = 6)
ari_mat=matrix(empty_ari,byrow = T,ncol = 6)
colnames(ari_mat)=c(paste("gibbs",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
colnames(mse_mat)=c(paste("gibbs",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))

write.csv(mse_mat,"C:/users/spenc/desktop/simulation_results/mse_05gibbs.csv")
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_05gibbs.csv")


######################################################
M=2
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation4/m20"
library(fda)
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=M*100)
N=length(real_label)
j=1
empty_mse=NULL
empty_ari=NULL
for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_ls
empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[c(1,3,5,7,9,11),1]))
  #j=1  gibbs; j=2  2021
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse=c(empty_mse,temp_mse)
}


mse_mat=matrix(empty_mse,byrow = T,ncol = 6)
ari_mat=matrix(empty_ari,byrow = T,ncol = 6)
colnames(ari_mat)=c(paste("gibbs",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
colnames(mse_mat)=c(paste("gibbs",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))

write.csv(mse_mat,"C:/users/spenc/desktop/simulation_results/mse_20gibbs.csv")
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_20gibbs.csv")

######################################################
M=1
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation2/ls/dt0630"

library(fda)
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=M*100)
N=length(real_label)
j=1
empty_mse=NULL
empty_ari=NULL
for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_ls
empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[c(1,3,5,7,9,11),1]))
  #j=1  gibbs; j=2  2021
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse=c(empty_mse,temp_mse)
}


mse_mat=matrix(empty_mse,byrow = T,ncol = 6)
ari_mat=matrix(empty_ari,byrow = T,ncol = 6)
colnames(ari_mat)=c(paste("gibbs",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
colnames(mse_mat)=c(paste("gibbs",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))

write.csv(mse_mat,"C:/users/spenc/desktop/simulation_results/mse_10gibbs.csv")
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_10gibbs.csv")

```




```{r}

M=0.5
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation4/m05"
temp_dir=dir(temp_dir_path)
library(fda)
N=length(real_label)
empty_ari=NULL

for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_ls
    empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[,1]))
}

ari_mat=matrix(empty_ari,byrow = T,ncol = 12)
colnames(ari_mat)=c(paste("gibbs",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")),paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_05.csv")

######################################################
M=2
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation4/m20"
temp_dir=dir(temp_dir_path)
library(fda)
N=length(real_label)
empty_ari=NULL

for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_ls
 empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[,1]))

}

ari_mat=matrix(empty_ari,byrow = T,ncol = 12)
colnames(ari_mat)=c(paste("gibbs",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")),paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_20.csv")

######################################################
M=1
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation2/ls/dt0630"

library(fda)
temp_dir=dir(temp_dir_path)
N=length(real_label)
empty_ari=NULL

for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_ls
 empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[,1]))

}

ari_mat=matrix(empty_ari,byrow = T,ncol = 12)
colnames(ari_mat)=c(paste("gibbs",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")),paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_10.csv")

```



lad函数

```{r}
parallel_simulation2_lad=function(seed_seq,M=0.5)
{set.seed(seed_seq)
  library(FdaCluReg)
fun_1=function(t){return(sin((pi*t/10))/5^0.5)}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/5^0.5)}#basis fun 2
function_list=list(fun_1,fun_2)#function list
sample_t=seq(0,10,0.1)#sampling time 
group_scale=c(100,100,100)*M#group scales
N=sum(group_scale)#number of samples
fda_coef_df=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df_list=list(fda_coef_df)
error_sd=0.2#standard error of observation error 
# generating X  
xij_temp=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df,sample_t=sample_t,error_sd = 0.2)
xij_list=list(xij_temp)

## generating Y
###parameter setting  
#
set.seed(1)
#
N=nrow(fda_coef_df)#sample size 
reg_error1=rnorm(N,0,1)*0.2#epsilon-1
reg_error2=rt(N,3)*0.2#epsilon-2
reg_error3=(rchisq(N,3)-3)*0.2#epsilon-3
#
reg_var1=rep(1,N)#sigma-1
reg_var2=0.5*fda_coef_df[,1]+0.4*fda_coef_df[,2]#sigma-2
#
reg_coef_df=as.matrix(cbind(c(rep(1,200*M),rep(-1,100*M)),c(rep(1,100*M),rep(-1,200*M))))
reg_coef_df_list=list(reg_coef_df)#for multi variables
reg_intercept=c(rep(3,100*M),rep(-3,100*M),rep(0,100*M))

##########################
yi_temp_n_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error1)
yi_temp_t_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error2)
yi_temp_chisq_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error3)


########################
yi_temp_n_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error1)
yi_temp_t_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error2)
yi_temp_chisq_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error3)

Y_list=vector("list",6);
Y_list[[1]]=yi_temp_n_homo
Y_list[[2]]=yi_temp_t_homo
Y_list[[3]]=yi_temp_chisq_homo
Y_list[[4]]=yi_temp_n_heter
Y_list[[5]]=yi_temp_t_heter
Y_list[[6]]=yi_temp_chisq_heter
names(Y_list)=c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")


library(fda)
basis_need=fourier_basis=create.fourier.basis(c(0,10),10)# basis function
#smoothing 
sample_t=seq(0,10,0.1)#sampling time points
K_seq=2:5
true_label=rep(1:3,each=100*M)
var_ratio=0.9
rounds=100
burning_period=20
lambda=0.2
ncomp_l=1

simulation2_res_lad=simulation_results_function(X_list =xij_list,
                             Y=Y_list,
                             basis=basis_need,
                             sample_t=sample_t,
                             var_ratio=var_ratio,
                             K_max=5,
                             true_label=true_label,
                             rounds=rounds,
                             burning_period=burning_period,
                             lambda = lambda,
                             method="lad",
                             ncomp_u=10,ncomp_l=ncomp_l,seed=seed_seq,type = c(F,T))
save(simulation2_res_lad,file = paste("C:/users/spenc/desktop/simulation_results/simulation4/m052021/lad/s4_",M,seed_seq,".RData",sep = ""))
print(seed_seq)
}


num_cores=10
library(parallel)
cl=makeCluster(num_cores)
clusterExport(cl,  envir = environment(),varlist =c("color_seq", "simulation_results_function"))
parLapply(cl,(1:100),parallel_simulation2_lad,M=0.5)
stopCluster(cl)
```
ls函数

```{r}
parallel_simulation2_ls=function(seed_seq,M=0.5)
{set.seed(seed_seq)
  library(FdaCluReg)
fun_1=function(t){return(sin((pi*t/10))/5^0.5)}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/5^0.5)}#basis fun 2
function_list=list(fun_1,fun_2)#function list
sample_t=seq(0,10,0.1)#sampling time 
group_scale=c(100,100,100)*M#group scales
N=sum(group_scale)#number of samples
fda_coef_df=cbind(rnorm(N,0,1),rnorm(N,0,2))#basis coef. for X construction
fda_coef_df_list=list(fda_coef_df)
error_sd=0.2#standard error of observation error 
# generating X  
xij_temp=xij_fun(function_list=function_list,fda_coef_df=fda_coef_df,sample_t=sample_t,error_sd = 0.2)
xij_list=list(xij_temp)

## generating Y
###parameter setting  
#
set.seed(1)
#
N=nrow(fda_coef_df)#sample size 
reg_error1=rnorm(N,0,1)*0.2#epsilon-1
reg_error2=rt(N,3)*0.2#epsilon-2
reg_error3=(rchisq(N,3)-3)*0.2#epsilon-3
#
reg_var1=rep(1,N)#sigma-1
reg_var2=0.5*fda_coef_df[,1]+0.4*fda_coef_df[,2]#sigma-2
#
reg_coef_df=as.matrix(cbind(c(rep(1,200*M),rep(-1,100*M)),c(rep(1,100*M),rep(-1,200*M))))
reg_coef_df_list=list(reg_coef_df)#for multi variables
reg_intercept=c(rep(3,100*M),rep(-3,100*M),rep(0,100*M))

##########################
yi_temp_n_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error1)
yi_temp_t_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error2)
yi_temp_chisq_homo=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var1,
               reg_error = reg_error3)


########################
yi_temp_n_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error1)
yi_temp_t_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error2)
yi_temp_chisq_heter=yi_fun(function_list = function_list,
               fda_coef_df_list  = fda_coef_df_list,
               reg_coef_df_list = reg_coef_df_list,
               reg_intercept = reg_intercept,
               reg_var = reg_var2,
               reg_error = reg_error3)

Y_list=vector("list",6);
Y_list[[1]]=yi_temp_n_homo
Y_list[[2]]=yi_temp_t_homo
Y_list[[3]]=yi_temp_chisq_homo
Y_list[[4]]=yi_temp_n_heter
Y_list[[5]]=yi_temp_t_heter
Y_list[[6]]=yi_temp_chisq_heter
names(Y_list)=c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")


library(fda)
basis_need=fourier_basis=create.fourier.basis(c(0,10),10)# basis function
#smoothing 
sample_t=seq(0,10,0.1)#sampling time points
K_seq=2:5
true_label=rep(1:3,each=100*M)
var_ratio=0.9
rounds=100
burning_period=20
lambda=0.2
ncomp_l=1

simulation2_res_ls=simulation_results_function(X_list =xij_list,
                             Y=Y_list,
                             basis=basis_need,
                             sample_t=sample_t,
                             var_ratio=var_ratio,
                             K_max=5,
                             true_label=true_label,
                             rounds=rounds,
                             burning_period=burning_period,
                             lambda = lambda,
                             method="ls",
                             ncomp_u=10,ncomp_l=ncomp_l,seed=seed_seq,type = c(F,T))
save(simulation2_res_ls,file = paste("C:/users/spenc/desktop/simulation_results/simulation4/m202021/ls/s4_",M,seed_seq,".RData",sep = ""))
print(seed_seq)
}


num_cores=10
library(parallel)
cl=makeCluster(num_cores)
clusterExport(cl,  envir = environment(),varlist =c("color_seq", "simulation_results_function"))
parLapply(cl,(1:100),parallel_simulation2_ls,M=2)
stopCluster(cl)
1
```


lad结果汇总   
```{r}
M=0.5
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation4/m052021/lad"

library(fda)
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=M*100)
N=length(real_label)

empty_mse=NULL
empty_ari=NULL
for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_lad
empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[c(2,4,6,8,10,12),1]))
  #j=1  gibbs; j=2  2021
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse=c(empty_mse,temp_mse)
}


mse_mat=matrix(empty_mse,byrow = T,ncol = 6)
ari_mat=matrix(empty_ari,byrow = T,ncol = 6)
colnames(ari_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
colnames(mse_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))

write.csv(mse_mat,"C:/users/spenc/desktop/simulation_results/mse_05lad.csv")
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_05lad.csv")
######################################################
M=2
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation4/m202021/lad"

library(fda)
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=M*100)
N=length(real_label)

empty_mse=NULL
empty_ari=NULL
for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_lad
 empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[c(2,4,6,8,10,12),1]))
  #j=1  gibbs; j=2  2021
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse=c(empty_mse,temp_mse)
}


mse_mat=matrix(empty_mse,byrow = T,ncol = 6)
ari_mat=matrix(empty_ari,byrow = T,ncol = 6)
colnames(ari_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
colnames(mse_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
write.csv(mse_mat,"C:/users/spenc/desktop/simulation_results/mse_20lad.csv")
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_20lad.csv")

######################################################
M=1
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation2/lad"

library(fda)
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=M*100)
N=length(real_label)

empty_mse=NULL
empty_ari=NULL
for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_lad
 empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[c(2,4,6,8,10,12),1]))
  #j=1  gibbs; j=2  2021
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse=c(empty_mse,temp_mse)
}


mse_mat=matrix(empty_mse,byrow = T,ncol = 6)
ari_mat=matrix(empty_ari,byrow = T,ncol = 6)
colnames(ari_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
colnames(mse_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
write.csv(mse_mat,"C:/users/spenc/desktop/simulation_results/mse_10lad.csv")
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_10lad.csv")
```

HL结果汇总   
```{r}
M=0.5
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation4/m052021/hl"

library(fda)
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=M*100)
N=length(real_label)

empty_mse=NULL
empty_ari=NULL
for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_hl
 empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[c(2,4,6,8,10,12),1]))
  #j=1  gibbs; j=2  2021
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse=c(empty_mse,temp_mse)
}


mse_mat=matrix(empty_mse,byrow = T,ncol = 6)
ari_mat=matrix(empty_ari,byrow = T,ncol = 6)
colnames(ari_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
colnames(mse_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
write.csv(mse_mat,"C:/users/spenc/desktop/simulation_results/mse_05hl.csv")
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_05hl.csv")
######################################################
M=2
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation4/m202021/hl"

library(fda)
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=M*100)
N=length(real_label)

empty_mse=NULL
empty_ari=NULL
for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_hl
 empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[c(2,4,6,8,10,12),1]))
  #j=1  gibbs; j=2  2021
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse=c(empty_mse,temp_mse)
}


mse_mat=matrix(empty_mse,byrow = T,ncol = 6)
ari_mat=matrix(empty_ari,byrow = T,ncol = 6)
colnames(ari_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
colnames(mse_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
write.csv(mse_mat,"C:/users/spenc/desktop/simulation_results/mse_20hl.csv")
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_20hl.csv")

######################################################
M=1
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation2/hl"

library(fda)
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=M*100)
N=length(real_label)

empty_mse=NULL
empty_ari=NULL
for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_hl
 empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[c(2,4,6,8,10,12),1]))
  #j=1  gibbs; j=2  2021
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse=c(empty_mse,temp_mse)
}


mse_mat=matrix(empty_mse,byrow = T,ncol = 6)
ari_mat=matrix(empty_ari,byrow = T,ncol = 6)
colnames(ari_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
colnames(mse_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
write.csv(mse_mat,"C:/users/spenc/desktop/simulation_results/mse_10hl.csv")
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_10hl.csv")
```

ls结果汇总   
```{r}
M=0.5
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation4/m052021/ls"

library(fda)
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=M*100)
N=length(real_label)

empty_mse=NULL
empty_ari=NULL
for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_ls
empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[c(2,4,6,8,10,12),1]))
  #j=1  gibbs; j=2  2021
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse=c(empty_mse,temp_mse)
}


mse_mat=matrix(empty_mse,byrow = T,ncol = 6)
ari_mat=matrix(empty_ari,byrow = T,ncol = 6)
colnames(ari_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
colnames(mse_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))

write.csv(mse_mat,"C:/users/spenc/desktop/simulation_results/mse_05ls.csv")
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_05ls.csv")
######################################################
M=2
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation4/m202021/ls"

library(fda)
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=M*100)
N=length(real_label)

empty_mse=NULL
empty_ari=NULL
for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_ls
 empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[c(2,4,6,8,10,12),1]))
  #j=1  gibbs; j=2  2021
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse=c(empty_mse,temp_mse)
}


mse_mat=matrix(empty_mse,byrow = T,ncol = 6)
ari_mat=matrix(empty_ari,byrow = T,ncol = 6)
colnames(ari_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
colnames(mse_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
write.csv(mse_mat,"C:/users/spenc/desktop/simulation_results/mse_20ls.csv")
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_20ls.csv")

######################################################
M=1
temp_dir_path="C:/users/spenc/desktop/simulation_results/simulation4/m102021/ls"

library(fda)
temp_dir=dir(temp_dir_path)
fun_1=function(t){return(sin((pi*t/10))/(5^0.5))}#basis fun 1
fun_2=function(t){return(sin((2*pi*t/10))/(5^0.5))}#basis fun 2
height_seq=NULL
K_max=5


real_beta_function1_1=function(x){return(fun_1(x)+fun_2(x))}
real_beta_function1_2=function(x){return(fun_1(x)-fun_2(x))}
real_beta_function1_3=function(x){return(-fun_1(x)-fun_2(x))}
beta_function_list=c(list(real_beta_function1_1),list(real_beta_function1_2),list(real_beta_function1_3))

real_label=rep(1:3,each=M*100)
N=length(real_label)

empty_mse=NULL
empty_ari=NULL
for (i in 1:length(temp_dir))
{
  load(paste(temp_dir_path,temp_dir[i],sep = "/"))
  temp_res=simulation2_res_ls
 empty_ari=c(empty_ari,as.numeric(temp_res$assement_all_mat[c(2,4,6,8,10,12),1]))
  #j=1  gibbs; j=2  2021
  empty_error_temp_file=matrix(rep(0,6*N),nrow = 6)#空的mse 当前文件
    for (l in 1:6) 
    {
      temp_label=as.numeric(temp_res[[j]][[l]]$selected_res$labels[[1]])
      N=length(temp_label)
      temp_fd_list=temp_res[[j]][[l]]$selected_res$beta_fd[[1]]
      temp_k_selected=temp_res$selected_K[(j-1)*6+l]
      temp_se_seq=NULL

      for (sample_index in 1:N) 
      {
        beta_fun=function(x){return(eval.fd(x,temp_fd_list[[temp_label[sample_index]]]))}
        temp_real_beta=beta_function_list[[real_label[sample_index]]]
        temp_se=integrate(function(x){return((beta_fun(x)-temp_real_beta(x))^2)},0,10)$value
        temp_se_seq=c(temp_se_seq,temp_se)
      }
      empty_error_temp_file[l,]=temp_se_seq
    }
     temp_mse=apply(empty_error_temp_file,1,mean)
     empty_mse=c(empty_mse,temp_mse)
}


mse_mat=matrix(empty_mse,byrow = T,ncol = 6)
ari_mat=matrix(empty_ari,byrow = T,ncol = 6)
colnames(ari_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
colnames(mse_mat)=c(paste("2021",c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")))
write.csv(mse_mat,"C:/users/spenc/desktop/simulation_results/mse_10ls.csv")
write.csv(ari_mat,"C:/users/spenc/desktop/simulation_results/ari_10ls.csv")
```


统计结果   
```{r}
m05=read.csv("C:/users/spenc/desktop/simulation_results/mse_05gibbs.csv")
m10=read.csv("C:/users/spenc/desktop/simulation_results/mse_10gibbs.csv")
m20=read.csv("C:/users/spenc/desktop/simulation_results/mse_20gibbs.csv")

m05lad=read.csv("C:/users/spenc/desktop/simulation_results/mse_05lad.csv")
m05ls=read.csv("C:/users/spenc/desktop/simulation_results/mse_05ls.csv")
m05hl=read.csv("C:/users/spenc/desktop/simulation_results/mse_05hl.csv")[-1,]

m20lad=read.csv("C:/users/spenc/desktop/simulation_results/mse_20lad.csv")
m20ls=read.csv("C:/users/spenc/desktop/simulation_results/mse_20ls.csv")
m20hl=read.csv("C:/users/spenc/desktop/simulation_results/mse_20hl.csv")[-(1:2),]

m10lad=read.csv("C:/users/spenc/desktop/simulation_results/mse_10lad.csv")
m10ls=read.csv("C:/users/spenc/desktop/simulation_results/mse_10ls.csv")
m10hl=read.csv("C:/users/spenc/desktop/simulation_results/mse_10hl.csv")

m20_boot=rbind(m20,m20[sample(87,13),])
all_mse=data.frame(m05[,2:7],m10[,2:7],m20_boot[,2:7])

plot_mse=all_mse[,c(1,7,13,2,8,14,3,9,15,4,10,16,5,11,17,6,12,18)]
plot_name=c("x","homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")
par(mfrow=c(1,3))
for (i in 2:7) 
{
  temp_mse_df=data.frame(A1=m05[,i],B1=m05ls[,i],C1=m05hl[,i],D1=m05lad[,i],
                         A2=m10[,i],B2=m10ls[,i],C2=m10hl[,i],D2=m10lad[,i],
                         A3=m20_boot[,i],B3=m20ls[,i],C3=m20hl[,i],D3=m20lad[,i])
  boxplot(temp_mse_df,ylim=c(0,2.5),col=rep(c("red","orange","purple","blue"),3),main=plot_name[i])
}


```

```{r}
m05=read.csv("C:/users/spenc/desktop/simulation_results/ari_05gibbs.csv")
m10=read.csv("C:/users/spenc/desktop/simulation_results/ari_10gibbs.csv")
m20=read.csv("C:/users/spenc/desktop/simulation_results/ari_20gibbs.csv")

m20_boot=rbind(m20,m20[sample(87,13),])
m05lad=read.csv("C:/users/spenc/desktop/simulation_results/ari_05lad.csv")
m05ls=read.csv("C:/users/spenc/desktop/simulation_results/ari_05ls.csv")
m05hl=read.csv("C:/users/spenc/desktop/simulation_results/ari_05hl.csv")[-(1),]

m20lad=read.csv("C:/users/spenc/desktop/simulation_results/ari_20lad.csv")
m20ls=read.csv("C:/users/spenc/desktop/simulation_results/ari_20ls.csv")
m20hl=read.csv("C:/users/spenc/desktop/simulation_results/ari_20hl.csv")[-(1:2),]

m10lad=read.csv("C:/users/spenc/desktop/simulation_results/ari_10lad.csv")
m10ls=read.csv("C:/users/spenc/desktop/simulation_results/ari_10ls.csv")
m10hl=read.csv("C:/users/spenc/desktop/simulation_results/ari_10hl.csv")



par(mfrow=c(1,3))
plot_name=c("x","homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")
for (i in c(2:7)) 
{
   temp_mse_df=data.frame(A1=m05[,i],B1=m05ls[,i],C1=m05hl[,i],D1=m05lad[,i],
                         A2=m10[,i],B2=m10ls[,i],C2=m10hl[,i],D2=m10lad[,i],
                         A3=m20_boot[,i],B3=m20ls[,i],C3=m20hl[,i],D3=m20lad[,i])
  boxplot(temp_mse_df,ylim=c(0,1),col=rep(c("red","orange","purple","blue"),2),main=plot_name[i])
}

mse_sample=matrix(rep(0,72),nrow = 6)
rownames(mse_sample)=c("homo_n","homo_t","homo_chisq","heter_n","heter_t","heter_chisq")
colnames(mse_sample)=paste(rep(c("s50","s100","s200"),each=4),rep(c("gibbs","ls","hl","lad"),3))

for (i in c(2:7)) 
{
mse_sample[i-1,]=c(c(mean(m05[,i]),mean(m05ls[,i]),mean(m05hl[,i]),mean(m05lad[,i])),
c(mean(m10[,i]),mean(m10ls[,i]),mean(m10hl[,i]),mean(m10lad[,i])),
c(mean(m20[,i]),mean(m20ls[,i]),mean(m20hl[,i]),mean(m20lad[,i])))
                  
}

```